name: "[Tests] Acceptance Testing"

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tests:
    uses: istic/shared-workflows/.github/workflows/python-tests.yml@main
    with:
      python_version: "3.12"
    secrets: inherit # pragma: allowlist secret
